on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version:
        - 10.x
        - 12.x
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm CI
      run: |
        npm ci
        git diff --exit-code
    - name: Generate docs
      run: |
        npm run docs
        git diff # FIXME add --exit-code if/when typedoc generates repeatable output
    - uses: mooyoul/tslint-actions@v1.1.1
      with:
        pattern: '*.ts'
        token: ${{ secrets.GITHUB_TOKEN }}

